# Task 1: Data Cleaning & Preprocessing

## Dataset: Northwind Database

### Objective
To inspect, clean, and preprocess the Northwind dataset using Python and Pandas so that the data can be used for further analysis and visualization.

In [9]:
import sqlite3

In [6]:
import pandas as pd

In [12]:
connection= sqlite3.connect("northwind.db")

In [13]:
print("connected to Northwind database successfully!")

connected to Northwind database successfully!

In [17]:
tables= pd.read_sql_query( "SELECT name FROM sqlite_master WHERE type='table';", connection)

In [18]:
tables

                    name
0             Categories
1        sqlite_sequence
2   CustomerCustomerDemo
3   CustomerDemographics
4              Customers
5              Employees
6    EmployeeTerritories
7          Order Details
8                 Orders
9               Products
10               Regions
11              Shippers
12             Suppliers
13           Territories

## 1.Importing the Dataset.

In [28]:
orders = pd.read_sql_query("SELECT * FROM Orders", connection)

In [30]:
orders.head()

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipVia,Freight,ShipName,ShipAddress,ShipCity,ShipRegion,ShipPostalCode,ShipCountry
0,10248,VINET,5,2016-07-04,2016-08-01,2016-07-16,3,16.75,Vins et alcools Chevalier,59 rue de l-Abbaye,Reims,Western Europe,51100,France
1,10249,TOMSP,6,2016-07-05,2016-08-16,2016-07-10,1,22.25,Toms Spezialitäten,Luisenstr. 48,Münster,Western Europe,44087,Germany
2,10250,HANAR,4,2016-07-08,2016-08-05,2016-07-12,2,25.00,Hanari Carnes,"Rua do Paço, 67",Rio de Janeiro,South America,05454-876,Brazil
3,10251,VICTE,3,2016-07-08,2016-08-05,2016-07-15,1,20.25,Victuailles en stock,"2, rue du Commerce",Lyon,Western Europe,69004,France
4,10252,SUPRD,4,2016-07-09,2016-08-06,2016-07-11,2,36.25,Suprêmes délices,"Boulevard Tirou, 255",Charleroi,Western Europe,B-6000,Belgium

## 2. Dataset Inspection

In [31]:
orders.shape

(16282, 14)

In [32]:
orders.columns

Index(['OrderID', 'CustomerID', 'EmployeeID', 'OrderDate', 'RequiredDate',
       'ShippedDate', 'ShipVia', 'Freight', 'ShipName', 'ShipAddress',
       'ShipCity', 'ShipRegion', 'ShipPostalCode', 'ShipCountry'],
      dtype='str')

In [33]:
orders.tail(10)

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,ShipVia,Freight,ShipName,ShipAddress,ShipCity,ShipRegion,ShipPostalCode,ShipCountry
16272,26520,MEREP,4,2013-07-27 20:23:48,2013-07-29 07:19:32,2013-08-11 07:23:03,2,164.00,Ana Trujillo Emparedados y helados,Avda. de la Constitución 2222,México D.F.,Central America,5021,Mexico
16273,26521,MAISD,5,2018-04-09 11:21:57,2018-04-22 07:02:15,2018-04-09 11:34:35,3,198.25,Bólido Comidas preparadas,"C/ Araquil, 67",Madrid,Southern Europe,28023,Spain
16274,26522,CACTU,4,2017-03-26 16:19:38,2017-05-01 18:42:00,2017-04-21 22:52:26,3,205.00,Bottom-Dollar Markets,23 Tsawassen Blvd.,Tsawassen,North America,T2F 8M4,Canada
16275,26523,ROMEY,6,2015-01-22 06:02:27,2015-02-14 10:37:42,2015-01-31 18:39:15,1,398.50,Around the Horn,Brook Farm Stratford St. Mary,Colchester,British Isles,CO7 6JX,UK
16276,26524,FOLIG,7,2018-08-13 19:06:09,2018-10-02 15:39:47,2018-08-15 09:42:05,1,52.00,Piccolo und mehr,Geislweg 14,Salzburg,Western Europe,5020,Austria
16277,26525,WHITC,6,2012-12-26 04:58:22,2013-01-07 03:47:01,2012-12-28 19:03:24,1,42.50,Wellington Importadora,"Rua do Mercado, 12",Resende,South America,08737-363,Brazil
16278,26526,WOLZA,9,2022-08-05 06:33:39,2022-09-01 05:09:08,2022-08-10 08:11:43,2,425.50,Tortuga Restaurante,Avda. Azteca 123,México D.F.,Central America,5033,Mexico
16279,26527,GOURL,4,2022-02-09 08:20:12,2022-02-19 13:46:17,2022-02-23 07:40:46,3,280.00,France restauration,"54, rue Royale",Nantes,Western Europe,44000,France
16280,26528,BLONP,9,2020-04-27 23:05:30,2020-05-22 20:22:49,2020-04-28 11:21:50,2,131.25,Great Lakes Food Market,2732 Baker Blvd.,Eugene,North America,97403,USA
16281,26529,DUMON,6,2023-01-10 05:40:51,2023-02-21 23:37:27,2023-01-10 09:47:23,2,447.25,Seven Seas Imports,90 Wadhurst Rd.,London,British Isles,OX15 4NB,UK

In [34]:
orders.dtypes

OrderID             int64
CustomerID            str
EmployeeID          int64
OrderDate             str
RequiredDate          str
ShippedDate           str
ShipVia             int64
Freight           float64
ShipName              str
ShipAddress           str
ShipCity              str
ShipRegion            str
ShipPostalCode        str
ShipCountry           str
dtype: object

In [35]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 16282 entries, 0 to 16281
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OrderID         16282 non-null  int64
 1   CustomerID      16282 non-null  str
 2   EmployeeID      16282 non-null  int64
 3   OrderDate       16282 non-null  str
 4   RequiredDate    16282 non-null  str
 5   ShippedDate     16261 non-null  str
 6   ShipVia         16282 non-null  int64
 7   Freight         16282 non-null  float64
 8   ShipName        16282 non-null  str
 9   ShipAddress     16282 non-null  str
 10  ShipCity        16282 non-null  str
 11  ShipRegion      16282 non-null  str
 12  ShipPostalCode  16110 non-null  str
 13  ShipCountry     16282 non-null  str
dtypes: float64(1), int64(3), str(10)
memory usage: 1.7 MB

## 3. Basic Statistical Summary

In [38]:
orders.describe()

            OrderID    EmployeeID       ShipVia       Freight
count  16282.000000  16282.000000  16282.000000  16282.000000
mean   18388.500000      4.968861      2.007739    248.585585
std     4700.352877      2.576741      0.814275    148.978822
min    10248.000000      1.000000      1.000000     10.250000
25%    14318.250000      3.000000      1.000000    117.250000
50%    18388.500000      5.000000      2.000000    245.250000
75%    22458.750000      7.000000      3.000000    377.250000
max    26529.000000      9.000000      3.000000    587.000000

## 4. Saving the Raw Dataset

In [41]:
orders.to_csv("orders_raw.csv",index=False)

In [42]:
print("Raw dataset saved successfully.")

Raw dataset saved successfully.

## 5. Missing Value Analysis

In [44]:
orders.isnull().sum()

OrderID             0
CustomerID          0
EmployeeID          0
OrderDate           0
RequiredDate        0
ShippedDate        21
ShipVia             0
Freight             0
ShipName            0
ShipAddress         0
ShipCity            0
ShipRegion          0
ShipPostalCode    172
ShipCountry         0
dtype: int64

In [48]:
missing_values=orders.isnull().sum()

In [49]:
missing_values[missing_values>0]

ShippedDate        21
ShipPostalCode    172
dtype: int64

## 6. Duplicate Record Analysis

In [51]:
orders.duplicated().sum()

np.int64(0)

In [52]:
orders[orders.duplicated()]

Empty DataFrame
Columns: [OrderID, CustomerID, EmployeeID, OrderDate, RequiredDate, ShippedDate, ShipVia, Freight, ShipName, ShipAddress, ShipCity, ShipRegion, ShipPostalCode, ShipCountry]
Index: []

In [56]:
orders = orders.drop_duplicates()

orders.duplicated().sum()

In [59]:
print("Duplicate rows:" , orders.duplicated().sum())

Duplicate rows: 0

## 7. Data Type Correction

In [60]:
orders.dtypes

OrderID             int64
CustomerID            str
EmployeeID          int64
OrderDate             str
RequiredDate          str
ShippedDate           str
ShipVia             int64
Freight           float64
ShipName              str
ShipAddress           str
ShipCity              str
ShipRegion            str
ShipPostalCode        str
ShipCountry           str
dtype: object

In [74]:
date_columns=["OrderDate","RequiredDate","ShippedDate"]

In [75]:
for column in date_columns: orders[column]=pd.to_datetime(orders[column], errors="coerce")

In [77]:
orders.dtypes

OrderID                    int64
CustomerID                   str
EmployeeID                 int64
OrderDate         datetime64[us]
RequiredDate      datetime64[us]
ShippedDate       datetime64[us]
ShipVia                    int64
Freight                  float64
ShipName                     str
ShipAddress                  str
ShipCity                     str
ShipRegion                   str
ShipPostalCode               str
ShipCountry                  str
dtype: object

In [78]:
orders["ShipCountry"].unique()

<StringArray>
[     'France',     'Germany',      'Brazil',     'Belgium', 'Switzerland',
   'Venezuela',     'Austria',      'Mexico',         'USA',      'Sweden',
     'Finland',       'Italy',       'Spain',          'UK',     'Ireland',
    'Portugal',      'Canada',     'Denmark',      'Poland',      'Norway',
   'Argentina']
Length: 21, dtype: str

In [79]:
orders["ShipCity"].unique()

<StringArray>
[          'Reims',         'Münster',  'Rio de Janeiro',            'Lyon',
       'Charleroi',            'Bern',          'Genève',         'Resende',
   'San Cristóbal',            'Graz',     'México D.F.',            'Köln',
     'Albuquerque',          'Bräcke',      'Strasbourg',            'Oulu',
         'München',         'Caracas',         'Seattle',          'Lander',
       'Cunewalde',         'Bergamo',         'Leipzig',           'Luleå',
  'Frankfurt a.M.',          'Madrid',    'Barquisimeto',   'Reggio Emilia',
          'London',       'Sao Paulo',            'Cork',       'Stuttgart',
         'Sevilla',       'Anchorage',        'Portland',          'Nantes',
           'Cowes',     'Brandenburg',           'Boise',          'Lisboa',
       'Marseille',        'Montréal',       'Kobenhavn',        'Toulouse',
        'Salzburg',      'Colchester',          'Aachen',       'Barcelona',
           'Århus',        'Warszawa',           'Elgin',         'Stavern',
       'Tsawassen', 'I. de Margarita',           'Lille',    'Buenos Aires',
          'Torino',        'Campinas',     'Walla Walla',       'Vancouver',
        'Mannheim',          'Eugene',       'Bruxelles',        'Kirkland',
   'San Francisco',        'Helsinki',           'Butte',          'Berlin',
           'Paris',      'Versailles']
Length: 70, dtype: str

In [81]:
text_columns=orders.select_dtypes(include=["str"]).columns

In [82]:
for columns in text_columns: orders[column]=orders[column]=orders[column].apply(lambda x:x.strip() if isinstance(x,str)else x)

In [83]:
orders.isnull().sum()

OrderID               0
CustomerID            0
EmployeeID            0
OrderDate         15452
RequiredDate      15452
ShippedDate       15473
ShipVia               0
Freight               0
ShipName              0
ShipAddress           0
ShipCity              0
ShipRegion            0
ShipPostalCode      172
ShipCountry           0
dtype: int64

In [84]:
if orders["Freight"].isnull().sum() > 0:
    orders["Freight"] = orders["Freight"].fillna(
        orders["Freight"].median()
    )

In [85]:
print("Dataset shape:")
print(orders.shape)

print("\nMissing values:")
print(orders.isnull().sum())

print("\nDuplicate records:")
print(orders.duplicated().sum())

print("\nData types:")
print(orders.dtypes)

Dataset shape:
(16282, 14)

Missing values:
OrderID               0
CustomerID            0
EmployeeID            0
OrderDate         15452
RequiredDate      15452
ShippedDate       15473
ShipVia               0
Freight               0
ShipName              0
ShipAddress           0
ShipCity              0
ShipRegion            0
ShipPostalCode      172
ShipCountry           0
dtype: int64

Duplicate records:
0

Data types:
OrderID                    int64
CustomerID                   str
EmployeeID                 int64
OrderDate         datetime64[us]
RequiredDate      datetime64[us]
ShippedDate       datetime64[us]
ShipVia                    int64
Freight                  float64
ShipName                     str
ShipAddress                  str
ShipCity                     str
ShipRegion                   str
ShipPostalCode               str
ShipCountry                  str
dtype: object

## 8. Exporting the cleaned datset

In [86]:
orders.to_csv(
    "orders_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [88]:
connection.close()

In [89]:
print("Database connection closed")

Database connection closed